spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/rag_admin}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:192.168.0.11}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:zhonghe_2h3b4bv57d3b}
      database: ${REDIS_DATABASE:0}
  threads:
    virtual:
      enabled: true

rag:
  internal:
    callback-token: ${RAG_INTERNAL_CALLBACK_TOKEN:rag-admin-internal-callback-token}
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://127.0.0.1:11434}
      timeout-seconds: ${OLLAMA_TIMEOUT_SECONDS:30}
  storage:
    minio:
      endpoint: ${MINIO_ENDPOINT:192.168.0.11}
      port: ${MINIO_PORT:9000}
      use-ssl: ${MINIO_USE_SSL:false}
      access-key: ${MINIO_ACCESS_KEY:root}
      secret-key: ${MINIO_SECRET_KEY:zh123456}
      bucket-name: ${MINIO_BUCKET_NAME:ragadmin}
      public-url: ${MINIO_PUBLIC_URL:http://192.168.0.11:9000}
  vector:
    milvus:
      base-url: ${MILVUS_BASE_URL:http://127.0.0.1:19530}
      token: ${MILVUS_TOKEN:root:Milvus}
      enabled: ${MILVUS_ENABLED:true}
