spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/rag_admin}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.0.11
      port: 6379
      password: zhonghe_2h3b4bv57d3b
      database: 0
  threads:
    virtual:
      enabled: true

rag:
  internal:
    callback-token: rag-admin-internal-callback-token
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      timeout-seconds: 30
  storage:
    minio:
      endpoint: 192.168.0.11
      port: 9000
      use-ssl: false
      access-key: root
      secret-key: zh123456
      bucket-name: hrsys
      public-url: http://192.168.0.11:9000
  vector:
    milvus:
      base-url: http://127.0.0.1:19530
      token: root:Milvus
      enabled: true
